on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Compile application
        run: ./mvnw package

      -
        name: Get current date
        id: date_generator
        run: echo "date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: src/main/docker/Dockerfile.jvm
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ github.repository_owner }}/quarkus-kubernetes:latest
          labels: |
              org.opencontainers.image.title="Quarkus Kubernetes"
              org.opencontainers.image.description="Quarkus application to test CI/CD pipeline"
              org.opencontainers.image.version=${{ github.ref_name }
              org.opencontainers.image.created=${{ steps.date_generator.outputs.date }}